### ISSUE TITLE
PTrace AMD support

### ISSUE THREAD

**Issue by DaClemens** [facebookexperimental/reverie#13]
I tried run this on two Zen AMD machines, it appears the timer code does not work and I couldn't find a way to disable it (i don't need precise timing)

I investigated and found the following:
- Apparently `fn check_for_zen_speclockmap()` contains an error for modern rust `asm!()`. I found it's x-adding a value as reference. I was able to fix this, it correctly returns an error now if the Zen workaround is not applied and returns Ok if the workaround is applied (it appears however, that the lock counter is already increased simply by whatever rust compiles to
- My devices are not in the magic number lists, I added the numbers which i _believe_ are right, but I don't really know the intrinsics here.

My patch
```patch
diff --git a/reverie-ptrace/src/timer.rs b/reverie-ptrace/src/timer.rs
index 09b3ef3..1353f17 100644
--- a/reverie-ptrace/src/timer.rs
+++ b/reverie-ptrace/src/timer.rs
@@ -100,6 +100,8 @@ pub(crate) fn get_rcb_perf_config() -> u64 {
         (0x06, 0x8E) | (0x06, 0x9E) => 0x5101c4,                // Intel Kabylake
         (0x06, 0xA5) | (0x06, 0xA6) => 0x5101c4,                // Intel Cometlake
         (0x06, 141) => 0x5101c4, // Intel Alder Lake (e.g. i7-11800H laptop)
+        (0x1f, 0x8) => 0x5100d1, // AMD Zen, Pinnacle Ridge
+        (0x23, 0x50) => 0x5100d1, // AMD Zen, Cezanne
         oth => panic!(
             "Unsupported processor with feature info: {:?}\n Full family_model: {:?}",
             fi, oth
diff --git a/reverie-ptrace/src/validation.rs b/reverie-ptrace/src/validation.rs
index 17f828a..eceeb0d 100644
--- a/reverie-ptrace/src/validation.rs
+++ b/reverie-ptrace/src/validation.rs
@@ -347,6 +347,7 @@ fn is_amd_zen(cpu_feature: FeatureInfo) -> bool {
         (cpu_type, ext_family_id),
         (
             0x00f10 // Naples, Whitehaven, Summit Ridge, Snowy Owl (Zen), Milan (Zen 3) (UNTESTED)
+            | 0x01780 // Pinnacle Ridge (Zen)
             | 0x10f10 // Raven Ridge, Great Horned Owl (Zen) (UNTESTED)
             | 0x10f80 // Banded Kestrel (Zen), Picasso (Zen+) (UNTESTED)
             | 0x20f00 // Dali (Zen) (UNTESTED)
@@ -358,7 +359,8 @@ fn is_amd_zen(cpu_feature: FeatureInfo) -> bool {
             0x8 | 0xa
         ) | (
             0x20f10 // Vermeer (Zen 3)
-            | 0x50f00, // Cezanne (Zen 3)
+            | 0x50f00 // Cezanne (Zen 3)
+            | 0x51e00, // Cezanne (Zen 3), mobile?
             0xa
         )
     )
@@ -407,12 +409,12 @@ fn check_for_zen_speclockmap() -> Result<(), PmuValidationError> {
     // A lock add is known to increase the perf counter we're looking at.
     #[cfg(not(feature = "llvm_asm"))]
     unsafe {
-        let _prev: usize;
+        let mut _prev: *mut usize;
         core::arch::asm!(
             "lock",
-            "xadd [{}], {}",
+            "add [{}], {}",
+            inout(reg) &to_add => _prev,
             in(reg) val,
-            inout(reg) to_add => _prev,
         )
     }
  
```

When running `cargo test`, some tests spuriosly seem to hang, i've observed `container::tests::pin_affinity_to_all_cores` to hang sometimes, whereas in other runs it would finish ok, but `container::tests::return_value` would hang always. The hangs got less frequent when i ran them sequentially (`-j 1`) and in release mode, but I think this is unrelated.

 Hope this helps!

**Comment by jasonwhite** [comment]
Thanks for the fixes! I created a PR with these fixes plus some others that I found as well (#14). The perf timer stuff isn't very well tested on AMD CPUs, so this has slipped through. I also double checked the family IDs and model IDs on https://en.wikichip.org/wiki/amd/cpuid, so it should be correct.

The usage of perf timers is entirely optional in Reverie. If `reverie::Guest::{set_timer,set_timer_precise}` are never called by the `Tool` implementer, then perf timers are never initialized and lack of AMD support shouldn't matter. Timers can be used for interrupting the guest after a precise number of branch instructions. If the examples in `reverie-examples` can run on your AMD CPU, then everything except for timers should work. Timers are the only case where having an AMD CPU should matter.
