### ISSUE TITLE
Please don't include_str! files from another crate in the same workspace

### ISSUE THREAD

**Issue by thoughtpolice** [facebookexperimental/reverie#17]
I'm trying to package Hermit for Nixpkgs, but unfortunately I've run into this error while building reverie: https://github.com/rust-lang/cargo/issues/7744

In short, this line:

https://github.com/facebookexperimental/reverie/blob/dba0b5b9b7827098d4d8b128ceb43072f92b3603/reverie/src/lib.rs#L9

Is problematic, because Nix vendors each package in the workspace and isolates it from each other. So the build fails because `include_str` fails because `../../README.md` can't be read. I believe this is the only instance of this problem, so fixing this should get things moving

I think an easy mid-way solution would just be to write a docstring for `reverie/lib.rs` with a small blurb pointing to this repo for more information rather than using `include_str` directly.

**Comment by jasonwhite** [comment]
Thanks for flagging this. Apologies for the slow reply; I've been on vacation for most of December. I'm a big Nix fan and use NixOS as my daily driver, so it'd be great to have a package for it. I'll fix this issue soon.
